import { arrayOf } from 'normalizr';
import boardSchema from './boardSchema';
import listSchema from './listSchema';
import cardSchema from './cardSchema';
import userSchema from './userSchema';
import commentSchema from './commentSchema';
import activitySchema from './activitySchema';
import trashSchema from './trashSchema';

export const BOARD = boardSchema;
export const BOARD_ARRAY = arrayOf(boardSchema);
export const LIST = listSchema;
export const LIST_ARRAY = arrayOf(listSchema);
export const CARD = cardSchema;
export const CARD_ARRAY = arrayOf(cardSchema);
export const USER = userSchema;
export const COMMENT = commentSchema;
export const ACTIVITY = activitySchema;
export const ACTIVITY_ARRAY = arrayOf(activitySchema);
export const TRASH_ITEM = trashSchema;
export const TRASH_ITEM_ARRAY = arrayOf(trashSchema);
