export const BOARDS_GET_ALL_REQUEST = 'BOARDS_GET_ALL_REQUEST';
export const BOARDS_GET_ALL_SUCCESS = 'BOARDS_GET_ALL_SUCCESS';
export const BOARDS_GET_ALL_ERROR = 'BOARDS_GET_ALL_ERROR';
export const BOARDS_GET_REQUEST = 'BOARDS_GET_REQUEST';
export const BOARDS_GET_SUCCESS = 'BOARDS_GET_SUCCESS';
export const BOARDS_GET_ERROR = 'BOARDS_GET_ERROR';
export const BOARDS_CREATE_REQUEST = 'BOARDS_CREATE_REQUEST';
export const BOARDS_CREATE_SUCCESS = 'BOARDS_CREATE_SUCCESS';
export const BOARDS_CREATE_ERROR = 'BOARDS_CREATE_ERROR';
export const BOARDS_REMOVE_REQUEST = 'BOARDS_REMOVE_REQUEST';
export const BOARDS_REMOVE_SUCCESS = 'BOARDS_REMOVE_SUCCESS';
export const BOARDS_REMOVE_ERROR = 'BOARDS_REMOVE_ERROR';
export const BOARDS_UPDATE_REQUEST = 'BOARDS_UPDATE_REQUEST';
export const BOARDS_UPDATE_SUCCESS = 'BOARDS_UPDATE_SUCCESS';
export const BOARDS_UPDATE_ERROR = 'BOARDS_UPDATE_ERROR';
export const BOARDS_ADD_LIST_ID = 'BOARDS_ADD_LIST_ID';
export const BOARDS_REMOVE_LIST_ID = 'BOARDS_REMOVE_LIST_ID';

export const BOARDS_INC_LISTS_LENGTH = 'BOARDS_INC_LISTS_LENGTH';
export const BOARDS_DEC_LISTS_LENGTH = 'BOARDS_DEC_LISTS_LENGTH';
export const BOARDS_INC_CARDS_LENGTH = 'BOARDS_INC_CARDS_LENGTH';
export const BOARDS_DEC_CARDS_LENGTH = 'BOARDS_DEC_CARDS_LENGTH';

export const BOARDS_TOGGLE_STARRED_SUCCESS = 'BOARDS_TOGGLE_STARRED_SUCCESS';
export const BOARDS_TOGGLE_STARRED_REQUEST = 'BOARDS_TOGGLE_STARRED_REQUEST';
export const BOARDS_TOGGLE_STARRED_ERROR = 'BOARDS_TOGGLE_STARRED_ERROR';

export const LISTS_CREATE_REQUEST = 'LISTS_CREATE_REQUEST';
export const LISTS_CREATE_SUCCESS = 'LISTS_CREATE_SUCCESS';
export const LISTS_CREATE_ERROR = 'LISTS_CREATE_ERROR';
export const LISTS_REMOVE_REQUEST = 'LISTS_REMOVE_REQUEST';
export const LISTS_REMOVE_SUCCESS = 'LISTS_REMOVE_SUCCESS';
export const LISTS_REMOVE_ERROR = 'LISTS_REMOVE_ERROR';
export const LISTS_UPDATE_REQUEST = 'LISTS_UPDATE_REQUEST';
export const LISTS_UPDATE_SUCCESS = 'LISTS_UPDATE_SUCCESS';
export const LISTS_UPDATE_ERROR = 'LISTS_UPDATE_ERROR';
export const LISTS_ADD_CARD_ID = 'LISTS_ADD_CARD_ID';
export const LISTS_REMOVE_CARD_ID = 'LISTS_REMOVE_CARD_ID';

export const CARDS_CREATE_REQUEST = 'CARDS_CREATE_REQUEST';
export const CARDS_CREATE_SUCCESS = 'CARDS_CREATE_SUCCESS';
export const CARDS_CREATE_ERROR = 'CARDS_CREATE_ERROR';
export const CARDS_REMOVE_REQUEST = 'CARDS_REMOVE_REQUEST';
export const CARDS_REMOVE_SUCCESS = 'CARDS_REMOVE_SUCCESS';
export const CARDS_REMOVE_ERROR = 'CARDS_REMOVE_ERROR';
export const CARDS_UPDATE_REQUEST = 'CARDS_UPDATE_REQUEST';
export const CARDS_UPDATE_SUCCESS = 'CARDS_UPDATE_SUCCESS';
export const CARDS_UPDATE_ERROR = 'CARDS_UPDATE_ERROR';
export const CARDS_ADD_COMMENT_ID = 'CARDS_ADD_COMMENT_ID';

export const CARD_GET_REQUEST = 'CARD_GET_REQUEST';
export const CARD_GET_SUCCESS = 'CARD_GET_SUCCESS';
export const CARD_GET_ERROR = 'CARD_GET_ERROR';

export const EDIT_FORM_SHOW = 'EDIT_FORM_SHOW';
export const EDIT_FORM_HIDE = 'EDIT_FORM_HIDE';

export const NOTIFICATIONS_CREATE = 'NOTIFICATIONS_CREATE';
export const NOTIFICATIONS_REMOVE = 'NOTIFICATIONS_REMOVE';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

export const SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_ERROR = 'SIGN_OUT_ERROR';

export const USER_GET_REQUEST = 'USER_GET_REQUEST';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_ERROR = 'USER_GET_ERROR';

export const COMMENTS_CREATE_REQUEST = 'COMMENTS_CREATE_REQUEST';
export const COMMENTS_CREATE_SUCCESS = 'COMMENTS_CREATE_SUCCESS';
export const COMMENTS_CREATE_ERROR = 'COMMENTS_CREATE_ERROR';

export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_ERROR = 'SEARCH_ERROR';

export const ACTIVITY_GET_REQUEST = 'ACTIVITY_GET_REQUEST';
export const ACTIVITY_GET_SUCCESS = 'ACTIVITY_GET_SUCCESS';
export const ACTIVITY_GET_ERROR = 'ACTIVITY_GET_ERROR';

export const PROGRESSBAR_SET_VALUE = 'PROGRESSBAR_SET_VALUE';
