export const BOARDS_GET_START = 'BOARDS_GET_START';
export const BOARDS_GET_SUCCESS = 'BOARDS_GET_SUCCESS';
export const BOARDS_GET_ERROR = 'BOARDS_GET_ERROR';

export const BOARDS_CREATE_START = 'BOARDS_CREATE_START';
export const BOARDS_CREATE_SUCCESS = 'BOARDS_CREATE_SUCCESS';

export const BOARDS_REMOVE_START = 'BOARDS_REMOVE_START';
export const BOARDS_REMOVE_SUCCESS = 'BOARDS_REMOVE_SUCCESS';

export const FULL_BOARD_GET_START = 'FULL_BOARD_GET_START';
export const FULL_BOARD_GET_SUCCESS = 'FULL_BOARD_GET_SUCCESS';

